### ISSUE TITLE
Provided high level descriptions for tasks and workflows without such docs

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/long-read-pipelines#24]

**Comment by kvg** [comment]
@SHuang-Broad to come up with the task ownership list for documentation responsibilities.

**Comment by SHuang-Broad** [comment]
## 15 root level WDLs

#### WDLs/root level workflows

```
CanuRunner.wdl
RaconRunner.wdl
QuastRunner.wdl
GuppyRunner.wdl
TestCromwell.wdl
MedakaRunner.wdl
NanopolishRunner.wdl
PB10xSingleFlowcell.wdl
ONT10xSingleFlowcell.wdl
TrioBinChildLongReads.wdl
PBCCSOnlySingleFlowcell.wdl
PB10xSingleProcessedSample.wdl
ONTWholeGenomeSingleFlowcell.wdl
PBCCSWholeGenomeSingleFlowcell.wdl
PBCLRWholeGenomeSingleFlowcell.wdl
```

#### subworkflows

| WDL FILE                    | LINE NUMBER | SUB-WORKFLOW                                                                               |
|-----------------------------|-------------|------------------------------------------------------------------------------------|
| AlignedMetrics.wdl          | 6           | workflow AlignedMetrics                                                            |
| AssembleMT.wdl              | 6           | workflow AssembleMT                                                                |
| AssignChildLongReads.wdl    | 5           | workflow AssignChildLongReadsGivenParentalKmerStats                                |
| C3POa.wdl                   | 6           | workflow C3POa                                                                     |
| CallSVs.wdl                 | 5           | workflow CallSVs                                                                   |
| CallSmallVariants.wdl       | 6           | workflow CallSmallVariants                                                         |
| Canu.wdl                    | 5           | workflow CorrectTrimAssemble                                                       |
| CollectParentsKmerStats.wdl | 6           | workflow CollectParentsKmerStats                                                   |
| DeepVariantLR.wdl           | 84          | workflow TestCallDeepVariant                                                       |
| DownloadFromSRA.wdl         | 21          | workflow DownloadFromSRA                                                           |
| Figures.wdl                 | 7           | workflow Figures                                                                   |
| GATKBestPractice.wdl        | 15          | workflow GATKBestPraciceForLR                                                      |
| Guppy.wdl                   | 5           | workflow Guppy                                                                     |
| Nanopolish.wdl              | 5           | workflow PolishAssembly                                                            |
| Peregrine.wdl               | 5           | workflow Peregrine                                                                 |
| PhaseReads.wdl              | 5           | workflow PhaseReads                                                                |
| UnalignedMetrics.wdl        | 6           | workflow UnalignedMetrics                                                          |

## 28 WDLs in "./tasks/"


```
Canu.wdl
Utils.wdl
C3POa.wdl
Guppy.wdl
Quast.wdl
Racon.wdl
Medaka.wdl
PBUtils.wdl
CallSVs.wdl
Figures.wdl
ONTUtils.wdl
NanoPlot.wdl
Finalize.wdl
Peregrine.wdl
Nanopolish.wdl
AlignReads.wdl
PhaseReads.wdl
AssembleMT.wdl
DeepVariantLR.wdl
AlignedMetrics.wdl
AssembleTarget.wdl
DownloadFromSRA.wdl
GATKBestPractice.wdl
UnalignedMetrics.wdl
AnnotateAdapters.wdl
CallSmallVariants.wdl
AssignChildLongReads.wdl
CollectParentsKmerStats.wdl
```

**Comment by SHuang-Broad** [comment]
## Assignment

Everyone, please pick the workflows that you authored and generate a check list on which

  * root level workflows
  * sub-workflows

and since all except utility WDLs are self-contained at this stage, 

  * all tasks in the picked WDL files.

And while we are addressing this issue, please also do the following in your PRs:

  * remove commented out code blocks
  * provide [`parameter_meta`](https://cromwell.readthedocs.io/en/stable/optimizations/FileLocalization/#wdl-10-or-later) for all tasks


Based on history, I've generated the following assignment. Feel free to pick more or unassign yourself if I made a mistake.

**Comment by SHuang-Broad** [comment]
#### @ericsong

**Root level**

- [ ] CanuRunner.wdl
- [ ] RaconRunner.wdl
- [ ] QuastRunner.wdl
- [ ] GuppyRunner.wdl
- [ ] MedakaRunner.wdl
- [ ] NanopolishRunner.wdl

**Task level**

- [ ] Canu.wdl
- [ ] Guppy.wdl
- [ ] Quast.wdl
- [ ] Racon.wdl
- [ ] Medaka.wdl
- [ ] Nanopolish.wdl

**Comment by SHuang-Broad** [comment]
#### @SHuang-Broad 

**Root level**

- [ ] TrioBinChildLongReads.wdl
- [ ] PBCCSOnlySingleFlowcell.wdl

**Task level**

- [ ] CallSVs.wdl
- [ ] Peregrine.wdl
- [ ] AlignReads.wdl
- [ ] DeepVariantLR.wdl
- [ ] DownloadFromSRA.wdl
- [ ] GATKBestPractice.wdl
- [ ] CallSmallVariants.wdl
- [ ] AssignChildLongReads.wdl
- [ ] CollectParentsKmerStats.wdl

**Comment by SHuang-Broad** [comment]
#### @kvg 

**Root level**

- [ ] TestCromwell.wdl
- [ ] PB10xSingleFlowcell.wdl
- [ ] ONT10xSingleFlowcell.wdl
- [ ] PB10xSingleProcessedSample.wdl
- [ ] PBCCSWholeGenomeSingleFlowcell.wdl
- [ ] PBCLRWholeGenomeSingleFlowcell.wdl
- [ ] ONTWholeGenomeSingleFlowcell.wdl

**1-off tasks?**

The following tasks exist in root level workflows. Consider if they should be moved to "tasks/".

| WORKFLOW                       | LINE NUMBER | TASK                   |
|--------------------------------|-------------|------------------------|
| TestCromwell.wdl               | 13          | task TestCromwellOnGCS |
| ONT10xSingleFlowcell.wdl       | 251         | task AnnotateAdapters  |
| PB10xSingleProcessedSample.wdl | 200         | task RevertBam         |
| PB10xSingleProcessedSample.wdl | 243         | task SplitBam          |
| PB10xSingleProcessedSample.wdl | 284         | task GetRunInfo        |


**Task level**

- [ ] Utils.wdl
- [ ] C3POa.wdl
- [ ] PBUtils.wdl
- [ ] Figures.wdl
- [ ] ONTUtils.wdl
- [ ] NanoPlot.wdl
- [ ] Finalize.wdl
- [ ] PhaseReads.wdl
- [ ] AssembleMT.wdl
- [ ] AssembleTarget.wdl
- [ ] AlignedMetrics.wdl
- [ ] UnalignedMetrics.wdl
- [ ] AnnotateAdapters.wdl

**Comment by SHuang-Broad** [comment]
closed by #424
